spring:
  jpa:
    show-sql: false

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.stat: OFF
    org.springframework.data.web: ERROR